KDC_PORT = 10000
BOB_PORT = 10001

KEY_LEN = 16
HOST_NAME_LEN = 8
NONCE_LEN = 8
TICKET_LEN = KEY_LEN + HOST_NAME_LEN + NONCE_LEN

RECV_BUF_SIZE = 4096

GREETING = b'I want to talk to you'
ALICE_ID = b'1'
BOB_ID = b'2'
KDC_ID = b'3'
TRUDY_ID = b'4'